name       : patchelf
version    : 0.14.3
release    : 5
source     :
    - https://github.com/NixOS/patchelf/archive/refs/tags/0.14.3.tar.gz : 827a8ca914c69413f1ca0d967a637980a24edf000a938531a77e663317c853bb
homepage   : https://github.com/NixOS/patchelf/
license    : GPL-3.0-or-later
component  : programming.tools
summary    : A small utility to modify the dynamic linker and RPATH of ELF executables
description: |
    PatchELF is a simple utility for modifying existing ELF executables and libraries. It can change the dynamic loader ("ELF interpreter") of executables, change or shrink the RPATH of executables and libraries, remove declared dependencies on dynamic libraries, and more.
setup      : |
    %reconfigure
build      : |
    %make
install    : |
    %make_install
    rm -rf $installdir/usr/share/doc
check      : |
    %make check
